name: daskwiki
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - abseil-cpp=20200225.2
  - aiobotocore=1.1.2
  - aiohttp=3.7.3
  - aioitertools=0.7.0
  - appdirs=1.4.4
  - argon2-cffi=20.1.0
  - arrow-cpp=1.0.1
  - arrow-cpp-proc=2.0.0
  - async-timeout=3.0.1
  - async_generator=1.10
  - attrs=20.3.0
  - aws-c-common=0.4.59
  - aws-c-event-stream=0.1.6
  - aws-checksums=0.1.10
  - aws-sdk-cpp=1.8.70
  - backcall=0.2.0
  - backports=1.0
  - backports.functools_lru_cache=1.6.1
  - bleach=3.2.1
  - bokeh=2.2.3
  - boost=1.72.0
  - boost-cpp=1.72.0
  - brotli=1.0.9
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - c-ares=1.16.1
  - ca-certificates=2020.10.14
  - cairo=1.16.0
  - certifi=2020.11.8
  - cffi=1.14.3
  - cfitsio=3.470
  - chardet=3.0.4
  - click=7.1.2
  - click-plugins=1.1.1
  - cligj=0.7.0
  - cloudpickle=1.6.0
  - colorcet=2.0.1
  - cryptography=3.2.1
  - curl=7.71.1
  - cyrus-sasl=2.1.27
  - cytoolz=0.11.0
  - dask=2.30.0
  - dask-core=2.30.0
  - datashader=0.11.1
  - datashape=0.5.4
  - decorator=4.4.2
  - defusedxml=0.6.0
  - distributed=2.30.1
  - dlpack=0.3
  - docutils=0.15.2
  - entrypoints=0.3
  - expat=2.2.9
  - faiss-proc=1.0.0
  - fastavro=1.1.1
  - fastparquet=0.4.1
  - fastrlock=0.5
  - fiona=1.8.13
  - fontconfig=2.13.1
  - freetype=2.10.4
  - freexl=1.0.5
  - fsspec=0.8.4
  - gdal=3.0.4
  - geopandas=0.8.1
  - geos=3.8.1
  - geotiff=1.6.0
  - gettext=0.19.8.1
  - gflags=2.2.2
  - giflib=5.2.1
  - glib=2.66.2
  - glog=0.4.0
  - grpc-cpp=1.33.2
  - hdf4=4.2.13
  - hdf5=1.10.6
  - heapdict=1.0.1
  - icu=64.2
  - idna=2.10
  - importlib-metadata=2.0.0
  - importlib_metadata=2.0.0
  - ipykernel=5.3.4
  - ipython=7.19.0
  - ipython_genutils=0.2.0
  - ipywidgets=7.5.1
  - jedi=0.17.2
  - jinja2=2.11.2
  - jmespath=0.10.0
  - joblib=0.17.0
  - jpeg=9d
  - json-c=0.13.1
  - json5=0.9.5
  - jsonschema=3.2.0
  - jupyter-server-proxy=1.5.0
  - jupyter_client=6.1.7
  - jupyter_core=4.7.0
  - jupyterlab=2.2.6
  - jupyterlab_pygments=0.1.2
  - jupyterlab_server=1.2.0
  - kealib=1.4.13
  - krb5=1.17.2
  - lcms2=2.11
  - ld_impl_linux-64=2.35.1
  - libblas=3.9.0
  - libcblas=3.9.0
  - libcurl=7.71.1
  - libdap4=3.20.6
  - libedit=3.1.20191231
  - libev=4.33
  - libevent=2.1.10
  - libfaiss=1.6.3
  - libffi=3.2.1
  - libgcc-ng=9.3.0
  - libgcrypt=1.8.7
  - libgdal=3.0.4
  - libgfortran-ng=9.3.0
  - libgfortran5=9.3.0
  - libglib=2.66.2
  - libgomp=9.3.0
  - libgpg-error=1.39
  - libgsasl=1.8.0
  - libhwloc=2.3.0
  - libiconv=1.16
  - libkml=1.3.0
  - liblapack=3.9.0
  - libllvm10=10.0.1
  - libnetcdf=4.7.4
  - libnghttp2=1.41.0
  - libntlm=1.4
  - libopenblas=0.3.12
  - libpng=1.6.37
  - libpq=12.3
  - libprotobuf=3.13.0.1
  - librdkafka=1.5.2
  - librmm=0.16.0
  - libsodium=1.0.18
  - libspatialindex=1.9.3
  - libspatialite=4.3.0a
  - libssh2=1.9.0
  - libstdcxx-ng=9.3.0
  - libthrift=0.13.0
  - libtiff=4.1.0
  - libutf8proc=2.5.0
  - libuuid=2.32.1
  - libuv=1.34.0
  - libwebp=1.1.0
  - libwebp-base=1.1.0
  - libxcb=1.13
  - libxml2=2.9.10
  - llvmlite=0.34.0
  - locket=0.2.0
  - lz4-c=1.9.2
  - markdown=3.3.3
  - markupsafe=1.1.1
  - mistune=0.8.4
  - msgpack-python=1.0.0
  - multidict=4.7.5
  - multipledispatch=0.6.0
  - munch=2.5.0
  - nbclient=0.5.1
  - nbconvert=6.0.7
  - nbformat=5.0.8
  - nccl=2.8.3.1
  - ncurses=6.2
  - nest-asyncio=1.4.3
  - networkx=2.5
  - nodejs=13.13.0
  - notebook=6.1.5
  - numba=0.51.2
  - numpy=1.19.4
  - nvtx=0.2.1
  - olefile=0.46
  - openjpeg=2.3.1
  - openssl=1.1.1h
  - orc=1.6.5
  - packaging=20.4
  - pandas=1.1.4
  - pandoc=2.11.1.1
  - pandocfilters=1.4.2
  - panel=0.10.2
  - param=1.10.0
  - parquet-cpp=1.5.1
  - parso=0.7.1
  - partd=1.1.0
  - pcre=8.44
  - pexpect=4.8.0
  - pickle5=0.0.11
  - pickleshare=0.7.5
  - pillow=8.0.1
  - pip=20.2.4
  - pixman=0.38.0
  - poppler=0.87.0
  - poppler-data=0.4.10
  - postgresql=12.3
  - proj=7.0.0
  - prometheus_client=0.9.0
  - prompt-toolkit=3.0.8
  - psutil=5.7.3
  - pthread-stubs=0.4
  - ptyprocess=0.6.0
  - pyarrow=1.0.1
  - pycparser=2.20
  - pyct=0.4.6
  - pyct-core=0.4.6
  - pydeck=0.5.0
  - pyee=7.0.4
  - pygments=2.7.2
  - pynvml=8.0.4
  - pyopenssl=19.1.0
  - pyparsing=2.4.7
  - pyppeteer=0.2.2
  - pyproj=2.6.1.post1
  - pyrsistent=0.17.3
  - pysocks=1.7.1
  - python=3.7.8
  - python-confluent-kafka=1.5.0
  - python-dateutil=2.8.1
  - python_abi=3.7
  - pytz=2020.4
  - pyviz_comms=0.7.6
  - pyyaml=5.3.1
  - pyzmq=20.0.0
  - re2=2020.11.01
  - readline=8.0
  - requests=2.25.0
  - rtree=0.9.4
  - s3fs=0.5.1
  - scikit-learn=0.23.2
  - scipy=1.5.3
  - send2trash=1.5.0
  - setuptools=49.6.0
  - shapely=1.7.1
  - simpervisor=0.3
  - six=1.15.0
  - snappy=1.1.8
  - sortedcontainers=2.3.0
  - spdlog=1.7.0
  - sqlite=3.33.0
  - streamz=0.6.1
  - tbb=2020.2
  - tblib=1.6.0
  - terminado=0.9.1
  - testpath=0.4.4
  - threadpoolctl=2.1.0
  - thrift=0.11.0
  - tiledb=1.7.7
  - tk=8.6.10
  - toolz=0.11.1
  - tornado=6.1
  - tqdm=4.52.0
  - traitlets=5.0.5
  - treelite=0.93
  - typing-extensions=3.7.4.3
  - typing_extensions=3.7.4.3
  - tzcode=2020a
  - urllib3=1.25.11
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - websockets=8.1
  - wheel=0.35.1
  - widgetsnbextension=3.5.1
  - wrapt=1.12.1
  - xarray=0.16.1
  - xerces-c=3.2.2
  - xz=5.2.5
  - yaml=0.2.5
  - yarl=1.6.3
  - zeromq=4.3.3
  - zict=2.0.0
  - zipp=3.4.0
  - zlib=1.2.11
  - zstd=1.4.5
  - pip:
    - boto3==1.16.25
    - botocore==1.19.25
    - s3transfer==0.3.3
    - s4cmd==2.1.0
    - treelite-runtime==0.93
